name: Generate JS Docs # this runs JSDocs on all JS files

on: [push] # the Github Action will activate "on" the event that you "push" to the repo

jobs: # the things being executed
  jsdocs: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependency
        run: npm install -g jsdoc

      - name: Making JS Docs
        run: jsdoc -r .

      - name: Commit and Push Docs
        run: jsdoc -r .
        
      - name: Commit and Push Docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update JS docs [skip ci]" || echo "No changes to commit"
          git push
